class UserNotExistError(Exception):
    pass


class UserExistError(Exception):
    pass
